### ISSUE TITLE
Default path "/"

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#20]
**Current behavior:**
When default path `"/"` is selected, there is no active tab in the navigation bar. 
**Desired behavior:**
When `"/"` is selected, the active tab shall be "**Events"**, like when  `"/home"` is selected.

**Comment by martindekov** [comment]
https://github.com/martindekov/event-organizer/blob/aa543201e71301c8f2cf18dfef067795fbc1ab14/resources/views/layouts/app.blade.php#L54

change this line to have `{{ Request::segment(1) === 'home' || '/' ? 'active text-white' : null }}"`
`active` is the CSS equivalent to selected
`text-white` is the font of the text in the selected area
