### ISSUE TITLE
"About" page enhancements

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#21]
**Current state:**
About page title _"Article or any other information."_ and some placeholder text.
**Desired state:**
About page title _"Bring the world together through live experiences"_
Add the following text instead of the placeholder:
`"EventO is a global platform for live experiences that allows anyone to create, share, find and attend events that fuel their passions and enrich their lives. From music festivals, marathons, conferences, community rallies, and fundraisers, to gaming competitions and air guitar contests. Our mission is to bring the world together through live experiences. "`

**Comment by martindekov** [comment]
Here:
https://github.com/martindekov/event-organizer/blob/5dc0c18a51cdc2ef91a8c5ed0191b7d458baf043/resources/views/pages/about.blade.php#L12

1. Change text in the `h3` tags to `Bring the world together through live experiences` 
2. Open PR

**Comment by martindekov** [comment]
Fixed in: https://github.com/martindekov/event-organizer/pull/28
