### ISSUE TITLE
"Login" page enhancements

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#22]
**Current state:**
The attached picture displays the current state:
**Desired state:**
Marked with red are all the enhancements that needs to be applied.
[https://drive.google.com/open?id=1MnvLp0A-qPfUcLoSSRbSLfuEOVlvF0U0](https://drive.google.com/open?id=1MnvLp0A-qPfUcLoSSRbSLfuEOVlvF0U0)

**Comment by martindekov** [comment]
Here half of the work:
https://github.com/martindekov/event-organizer/blob/e1a04e29f89ce2826ae76c31a1659b00ec3cb2b2/resources/views/auth/login.blade.php#L65
1. Fix Dont -> Don't
2. Open PR

**Comment by martindekov** [comment]
Fixed in: https://github.com/martindekov/event-organizer/pull/28
