### ISSUE TITLE
"Sign up" page enhancements 

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#23]
Current state:
The attached picture displays the current state:
Desired state:
Marked with red are all the enhancements that needs to be applied.
[https://drive.google.com/open?id=1TCTIoSCCdW4Kc8C5ZRCjkty-dhgifo6F](https://drive.google.com/open?id=1TCTIoSCCdW4Kc8C5ZRCjkty-dhgifo6F)

**Comment by martindekov** [comment]
1. Apply following fixes
https://github.com/martindekov/event-organizer/blob/49aabbb9abe63fd6ba6f921d34b1a221f43b7210/resources/views/auth/register.blade.php#L102 `placeholder="First name"` -> `placeholder="Last name"`
https://github.com/martindekov/event-organizer/blob/49aabbb9abe63fd6ba6f921d34b1a221f43b7210/resources/views/auth/register.blade.php#L389
`placeholder="zip"` -> `placeholder="Zip"`
https://github.com/martindekov/event-organizer/blob/49aabbb9abe63fd6ba6f921d34b1a221f43b7210/resources/views/auth/register.blade.php#L405
`placeholder="Address line"` -> `placeholder="Address line 1"`
2. Open PR

**Comment by martindekov** [comment]
Fixed in: https://github.com/martindekov/event-organizer/pull/28 by @elvisyordanov
