### ISSUE TITLE
"Event details" page

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#26]
Create **"Event details"** page following the attached mock-up:
[https://drive.google.com/open?id=10hUMBXaRauTxeiV7OVPtGSYkD2qe_447](https://drive.google.com/open?id=10hUMBXaRauTxeiV7OVPtGSYkD2qe_447)

**Comment by martindekov** [comment]
Closed as per https://github.com/martindekov/event-organizer/pull/36 and https://github.com/martindekov/event-organizer/pull/36
