### ISSUE TITLE
Dropdown menu issue

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#44]
Current state:
When "My events" is clicked to expand,  the whole "My account" drop down menu shrinks.

Desired behavior:
When "My events" is clicked to expand,  the whole "My account" drop down menu stays expanded

![image](https://user-images.githubusercontent.com/17002017/73375565-a22b6e80-42c4-11ea-941b-44f30c0db597.png)

**Comment by martindekov** [comment]
Closed in #55
