### ISSUE TITLE
Upload pictures issue

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#45]
Current state:
Users can upload pictures to future events.

Desired state:
Pictures can be uploaded only to past  events, only by user with role "Organizer", clients should be able to decide whether  the gallery is public or private

> • Организатора качва галерия за събитието, съдържаща снимков материал
>показващ хронологията на събитието;
>• Клиента решава дали да направи галерията публична или не;

**Comment by martindekov** [comment]
Closed in #56

**Comment by martindekov** [comment]
Closed in #56
