### ISSUE TITLE
No events are displayed in the calendar

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#47]
Current state:
No events public or private are displayed in the calendar

Desired state:
Each day of the month should have a number of events in the calendar square box , and when pressed on the right side should appear a list with all the events for this date along with create button.
Registered users should be able to see their personal and all public events, users with no registration see only public events. 
When there are no events for a particular day, the create event button can stay.

![image](https://user-images.githubusercontent.com/17002017/73376760-a35d9b00-42c6-11ea-9a98-32732675880e.png)

**Comment by martindekov** [comment]
Closed in #57
