### ISSUE TITLE
Remove "My event requests" from My Account dropdown menu for organizers

### ISSUE THREAD

**Issue by ZdravkaDzhaleva** [martindekov/event-organizer#54]
Current state:
Users with role "organizer" have "My event requests" in **My Account** dropdown menu

Desired state:
Users with role "organizer" do not have "My event requests" in **My account** dropdown menu

![image](https://user-images.githubusercontent.com/17002017/73467869-9c995b80-438c-11ea-9b11-5fd8acf4459f.png)

**Comment by martindekov** [comment]
Closed in #55
