### ISSUE TITLE
Event calendar

### ISSUE THREAD

**Issue by martindekov** [martindekov/event-organizer#9]
Event calendar for all approved events should be present

- [ ] Add event calendar which will show basic information for **all** events which have their flag true for approved
- [ ] (OPTIONAL IMO) Add personal calendar which will show **all events by the Client**

As per: https://e-edu.nbu.bg/pluginfile.php/1147957/mod_resource/content/0/CSCB024_Event_organizer.pdf
![image](https://user-images.githubusercontent.com/34942004/70561473-2dc13280-1b93-11ea-8184-357f2649733f.png)

**Comment by ZdravkaDzhaleva** [comment]
The following mock-up shall be followed:
[https://drive.google.com/open?id=1h9TrKh-1VruCJg4eLL9b5wSR2UzBCfQ1](https://drive.google.com/open?id=1h9TrKh-1VruCJg4eLL9b5wSR2UzBCfQ1)

**Comment by martindekov** [comment]
Closed as per https://github.com/martindekov/event-organizer/pull/34
